// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "goals.getAllGoals", input: GetAllGoalsArgs, result: Goal[] } | 
        { key: "hello.sayHi", input: never, result: string } | 
        { key: "notes.get", input: GetNotesArgs, result: Note[] } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "notes.create", input: CreateNoteArgs, result: Note } | 
        { key: "notes.delete", input: DeleteNoteArgs, result: Note } | 
        { key: "notes.edit", input: EditNoteArgs, result: Note },
    subscriptions: never
};

export type GetNotesArgs = { workspace_id: number }

export type EditNoteArgs = { id: number; title: string; content: string }

export type DeleteNoteArgs = { id: number }

export type GetAllGoalsArgs = { workspace_id: number }

export type CreateNoteArgs = { workspace_id: number }

export type Goal = { id: number; name: string; description: string; status: number; date_from: string | null; date_to: string | null; date_created: string; date_updated: string; workspace_id: number }

export type Note = { id: number; title: string; content: string; date_created: string; date_updated: string; workspace_id: number }
